# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89ec0ac198e6898a07f0fc3865071c3f"
application_url = "https://bundle-app-discount-outrageldn.vercel.app"
embedded = true
name = "Bundle App - Outrage"
handle = "bundle-app-outrage-ldn"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_cart_transforms"

[auth]
redirect_urls = ["https://bundle-app-discount-outrageldn.vercel.app/auth/callback", "https://bundle-app-discount-outrageldn.vercel.app/auth/shopify/callback", "https://bundle-app-discount-outrageldn.vercel.app/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://bundle-app-discount-outrageldn.vercel.app/storefront/bundles"
subpath = "bundles"
prefix = "apps"
